variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'     
    SolutionBaseName: 'DFC.App.FindACourse'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.1
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

jobs:

#Build and test resources
- job: BuildArmTemplates
  steps:
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: $(ArmTemplateRoot)
      SolutionBaseName: $(SolutionBaseName)

  - task: CopyFiles@2
    displayName: 'Copy Page Registration to Staging'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/Resources/PageRegistration'
      TargetFolder: $(build.artifactstagingdirectory)/PageRegistrations
      Contents: |
        *.json

  - task: PublishPipelineArtifact@0
    displayName: Publish Pipeline Artifact
    inputs:
      targetPath: $(build.artifactstagingdirectory)/PageRegistrations
      artifactName: $(SolutionBaseName).PageRegistrations

#Build and test application
- job: BuildDotNetCore
  displayName: Build-DotNetCore
  steps:
  # Build DFC.App.RelatedCareers
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 3.1.101
      PublishWebApp: true
      
#Build UI functional Tests
- job: Builduifunctionaltests
  displayName: Build UI functional tests
  steps:
# Build all UI Functional Tests that ends with UI.FunctionalTests
  - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).UI.FunctionalTests
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 3.1.101