name: convert-and-copy-to-azure-blob
on: push
    
jobs:

  #builds_json:
  builds:
    runs-on: ubuntu-latest      
    steps:

    - uses: actions/checkout@v2

    # - uses: "finnp/create-file-action@master"
    #   env:
    #     FILE_NAME: "./Tools/ImportExportTool/Data/output.json"
    #     FILE_DATA: ""
    
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - run: chmod +x "./Tools/ImportExportTool/Data/csv2json.bash"

    - name: convert-to-json
      run: ./Tools/ImportExportTool/Data/csv2json.bash "./Tools/ImportExportTool/Data/2022-01-06-CurrentLiveData.csv" > "./Tools/ImportExportTool/Data/Output/output.json"
      shell: bash

  #builds_copy:
  #  steps:
    - name: azure-blob-copy-action
      uses: ulaval/azure-blob-copy-action@v1
      with:
        action: upload
        connection_string: ${{ secrets.CONNECTION_STRING }}
        container_name: searchfeedjson
        blob_directory: ""
        local_directory: ./Tools/ImportExportTool/Data/Output
